# Generated by Django 3.2.23 on 2024-06-21 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(max_length=254, verbose_name='Your name*')),
                ('message_email', models.EmailField(max_length=254, verbose_name='Your email address')),
                ('message_mobile', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Your phone number')),
                ('message', models.TextField(max_length=4000, verbose_name='Your message*')),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
